---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-config-v1
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: tank-sc