---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm/
      chart: nextcloud
      version: 2.11.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nextcloud
      tag: 22.2.0
    env:
      TZ: "Europe/Lisbon"
    ingress:
      enabled: true
      ClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        hajimari.io/enable: "true"
        hajimari.io/icon: "text"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      tls:
        - hosts:
            - "nextcloud.${SECRET_DOMAIN}"
          secretName: "nextcloud-${SECRET_DOMAIN//./-}-tls"
    nextcloud:
      host: nextcloud.mike-server.ovh
      username: admin
      password: admin
    redis:
      enabled: true
    cronjob:
      enabled: true
    persistence:
        enabled: true
        existingClaim: nextcloud-config-v1
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
