---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs-zfslocalpv
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://openebs.github.io/zfs-localpv
      chart: zfs-localpv
      version: 1.9.8
      sourceRef:
        kind: HelmRepository
        name: openebs-zfslocalpv-charts
        namespace: flux-system
      interval: 5m
